name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Modificalo se utilizzi main o un altro branch come principale
  workflow_dispatch:  # Permette l'esecuzione manuale

# Imposta i permessi necessari per il token GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Consenti una sola implementazione simultanea
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Extract repository name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        
      - name: Build with correct base-href
        run: npm run build -- --base-href="/${{ env.REPO_NAME }}/"
        
      - name: Debug output directory
        run: |
          ls -la dist
          ls -la dist/steem-faucet-game || echo "Non esiste dist/steem-faucet-game"
          find dist -type d | sort
          
      - name: Create .nojekyll file
        run: |
          touch dist/steem-faucet-game/browser/.nojekyll
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Imposta il percorso corretto per l'output di Angular v17+
          path: './dist/steem-faucet-game/browser'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4